# Generated by Django 6.0.5 on 2026-05-08 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomicInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gene_symbol', models.CharField(max_length=50)),
                ('variant', models.CharField(max_length=255)),
                ('biomarker_category', models.CharField(blank=True, max_length=100)),
                ('clinical_significance', models.CharField(choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low'), ('uncertain', 'Uncertain')], default='uncertain', max_length=20)),
                ('evidence_summary', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('observed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomic_insights', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
