# Generated by Django 6.0.5 on 2026-05-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomicinsight',
            name='is_actionable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genomicinsight',
            name='report_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='genomicinsight',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('flagged', 'Flagged')], default='pending', max_length=20),
        ),
    ]
