# Generated by Django 6.0.5 on 2026-05-13 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomics', '0002_genomicinsight_is_actionable_and_more'),
        ('patients', '0003_alter_patientprofile_consent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomicinsight',
            name='gene_symbol',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Gene symbol must contain only letters, numbers, underscores, periods, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9_.-]*$')]),
        ),
        migrations.AddIndex(
            model_name='genomicinsight',
            index=models.Index(fields=['patient', 'gene_symbol', 'variant'], name='genomics_ge_patient_444a70_idx'),
        ),
        migrations.AddIndex(
            model_name='genomicinsight',
            index=models.Index(fields=['patient', 'is_actionable', '-created_at'], name='genomics_ge_patient_744e40_idx'),
        ),
    ]
