# Generated by Django 6.0.5 on 2026-05-08 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('rationale', models.TextField()),
                ('evidence_references', models.JSONField(blank=True, default=list)),
                ('suggested_options', models.JSONField(blank=True, default=list)),
                ('contraindication_warnings', models.JSONField(blank=True, default=list)),
                ('missing_data_flags', models.JSONField(blank=True, default=list)),
                ('uncertainty_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs Review'), ('approved', 'Approved'), ('overridden', 'Overridden'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('insufficient_data', 'Insufficient Data')], default='insufficient_data', max_length=30)),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('clinician_review_required', models.BooleanField(default=True)),
                ('generated_by', models.CharField(default='system', max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
