# Generated by Django 6.0.5 on 2026-05-11 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomics', '0002_genomicinsight_is_actionable_and_more'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecommendation',
            name='intended_use_notice',
            field=models.TextField(default='Clinical decision support only. Requires clinician review before action.'),
        ),
        migrations.AddField(
            model_name='treatmentrecommendation',
            name='primary_genomic_insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='genomics.genomicinsight'),
        ),
    ]
