# Generated by Django 6.0.5 on 2026-05-08 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex_at_birth', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('intersex', 'Intersex'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('diagnoses', models.JSONField(blank=True, default=list)),
                ('comorbidities', models.JSONField(blank=True, default=list)),
                ('medications', models.JSONField(blank=True, default=list)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('lifestyle_factors', models.JSONField(blank=True, default=dict)),
                ('clinical_notes_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
