# Generated by Django 6.0.5 on 2026-05-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='consent_status',
            field=models.CharField(default='pending_review', max_length=50),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='disease_progression_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='record_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
