# Generated by Django 6.0.5 on 2026-05-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientprofile_consent_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='consent_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('granted', 'Granted'), ('active', 'Active'), ('consented', 'Consented'), ('denied', 'Denied'), ('revoked', 'Revoked')], default='pending_review', max_length=50),
        ),
    ]
