# Generated by Django 6.0.5 on 2026-05-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('recommendation_created', 'Recommendation Created'), ('recommendation_updated', 'Recommendation Updated'), ('recommendation_review_requested', 'Recommendation Review Requested'), ('review_submitted', 'Review Submitted'), ('review_approved', 'Review Approved'), ('review_overridden', 'Review Overridden'), ('review_rejected', 'Review Rejected')], max_length=50),
        ),
    ]
