# Generated by Django 6.0.5 on 2026-05-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalreview',
            name='limitations_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalreview',
            name='missing_data_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
